### ISSUE TITLE
Shreya Ahuja - Accounts and Logins

### ISSUE THREAD

**Issue by shreya-ahujaa** [VidhiKulkarni/teamlace#31]
- [x] [Hack #1](https://github.com/VidhiKulkarni/nighthawk_csp/commit/37ae8e94e7ab3e2760ae3a9b355165ed7dd63105): Add Phone Number to Sign Up / Authorization screen
- [x] Hack #2:  Add logout to CRUD screen
- [x] [Hack #3](https://github.com/VidhiKulkarni/nighthawk_csp/commit/ea53af937358be0845b9b7c20b6a06522cf2b36d): Add login_required to another portion of the project
- [x] Create Task [Written Responses](https://shreya-ahujaa.github.io/shreya.individual/createtask) and Code on IntelliJ

**Comment by Reinhardtlotter** [comment]
Reinhardt And Valerie comment: 5/5 great work shown. Seems ready to develop PBL and submit Create Task. Madlibs was an impressive idea and implementation. Hacks were done correctly and shown effectively.
