### ISSUE TITLE
Week 1 Team Review

### ISSUE THREAD

**Issue by Rebecca-123** [VidhiKulkarni/teamlace#42]
Runtime Link: gidas.ml
Score: 0.9/1

- [x] AWS is a must for every team for weekly reviews(Deployment managers see Mr.M for a PUSD AWS account)
- [x] Minimum of 3 Scrum Team Review Tickets
   - [x] [Technical Requirements](https://github.com/VidhiKulkarni/teamlace/issues/38)
   - [x] [Home Page](https://github.com/VidhiKulkarni/teamlace/issues/7)
   - [x] [Meet our Team Page](https://github.com/VidhiKulkarni/teamlace/issues/16)
- [x] Checkpoint with Individual progress and meeting Individual Expectations
- [x] Checkpoint with Scrum Master and meeting Master plan
- [x] Runtime of Project updated and online
- [x] Create [Live Review Ticket with Master Plan updates](https://github.com/VidhiKulkarni/teamlace/issues/44)
- [x] Score of 1 point, .9 maximum
- [x] Meeting [sponsor objectives](https://github.com/VidhiKulkarni/teamlace/issues/44)
- [x] Total score for each individual

**Scoring**
[Shreya Ahuja](https://github.com/shreya-ahujaa/shreya.individual/issues/9): 2.6/3
[Vidhi Kulkarni](https://github.com/VidhiKulkarni/teamlace/issues/45): 2.7/3
[William Li](https://github.com/3ghin5/hatelace/issues/7): 2.7/3
[Rebecca Su](https://github.com/VidhiKulkarni/teamlace/issues/39): 2.7/3
